version: "3.9"

#1.5 unidades de CPU e 550MB de memória
#TODO: create script to validate limits

services:
  api01: &api
    image: rinha2024q1quarkus:latest
    network_mode: "host"
    restart: on-failure
    hostname: api01
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://localhost:5432/rinha
      - QUARKUS_HTTP_PORT=8081
    # ports:
      # - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          # cpus: "0.25"
          memory: "100MB"
          cpus: "1.0"
#            memory: "300MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://localhost:5432/rinha
      - QUARKUS_HTTP_PORT=8082
    # ports:
    #   - "8082:8080"

  nginx:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./nginx2.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    # ports:
      # - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "300MB"

  db:
    image: postgres:latest
    network_mode: "host"
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "rinha", "-U", "admin" ]
      interval: 2s
      timeout: 2s
      retries: 5
    # ports:
      # - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql:ro
    deploy:
      resources:
        limits:
          # cpus: "0.90"
          cpus: "1.0"
          memory: "330MB"

# networks:
  # default:
    # driver: bridge
    # name: rinha-nginx-2024q1
